param(
  [string]$User = "root",
  [string]$Password,
  [string]$ServerHost = "localhost",
  [int]$Port = 3306,
  [string]$MysqlPath,
  [switch]$IncludeSampleData,
  [switch]$ResetDatabase
)

function Resolve-MysqlPath {
  param(
    [string]$ExplicitPath
  )

  if ($ExplicitPath) {
    if (Test-Path -LiteralPath $ExplicitPath) {
      return (Resolve-Path -LiteralPath $ExplicitPath).Path
    }

    throw "mysql.exe was not found at '$ExplicitPath'."
  }

  $command = Get-Command mysql.exe -ErrorAction SilentlyContinue
  if ($command) {
    return $command.Source
  }

  $candidates = @(
    "C:\Program Files\MySQL\MySQL Server 8.0\bin\mysql.exe",
    "C:\Program Files\MySQL\MySQL Server 8.4\bin\mysql.exe",
    "C:\Program Files\MySQL\MySQL Workbench 8.0\mysql.exe",
    "C:\xampp\mysql\bin\mysql.exe"
  )

  foreach ($candidate in $candidates) {
    if (Test-Path -LiteralPath $candidate) {
      return $candidate
    }
  }

  throw "Could not find mysql.exe. Add MySQL to PATH or pass -MysqlPath."
}

function ConvertTo-PlainText {
  param(
    [Security.SecureString]$SecureString
  )

  $bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($SecureString)
  try {
    return [Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr)
  }
  finally {
    [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)
  }
}

function Initialize-SampleUploads {
  param(
    [string]$RepositoryRoot
  )

  $uploadsDir = Join-Path $RepositoryRoot "uploads"
  if (-not (Test-Path -LiteralPath $uploadsDir)) {
    New-Item -ItemType Directory -Path $uploadsDir | Out-Null
  }

  $sampleDataPath = Join-Path $scriptDir "sample_data.sql"
  $sampleSql = Get-Content -LiteralPath $sampleDataPath -Raw
  $uploadMatches = [regex]::Matches($sampleSql, "uploads/([^']+)")
  $sampleUploads = @()

  foreach ($match in $uploadMatches) {
    $fileName = $match.Groups[1].Value
    if ([string]::IsNullOrWhiteSpace($fileName)) {
      continue
    }

    if ($sampleUploads.FileName -contains $fileName) {
      continue
    }

    $matterHint = ($fileName -replace "\.[^.]+$", "") -replace "_", " "
    $sampleUploads += @{
      FileName = $fileName
      Matter = $matterHint
    }
  }

  foreach ($sampleUpload in $sampleUploads) {
    $targetPath = Join-Path $uploadsDir $sampleUpload.FileName
    if (Test-Path -LiteralPath $targetPath) {
      continue
    }

    $placeholderContent = @(
      "Sample upload placeholder generated by backend/sql/init_db.ps1",
      "Matter: $($sampleUpload.Matter)",
      "File: $($sampleUpload.FileName)",
      "Replace this placeholder with a real demo file at any time."
    )

    Set-Content -LiteralPath $targetPath -Value $placeholderContent -Encoding UTF8
  }
}

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = (Resolve-Path (Join-Path $scriptDir "..\..")).Path
$mysqlExe = Resolve-MysqlPath -ExplicitPath $MysqlPath

if (-not $Password) {
  $securePassword = Read-Host "Enter MySQL password for user '$User'" -AsSecureString
  $Password = ConvertTo-PlainText -SecureString $securePassword
}

$sqlFiles = @(
  (Join-Path $scriptDir "schema.sql"),
  (Join-Path $scriptDir "triggers.sql"),
  (Join-Path $scriptDir "procedures.sql"),
  (Join-Path $scriptDir "views_reports.sql")
)

if ($IncludeSampleData) {
  $sampleDataPath = Join-Path $scriptDir "sample_data.sql"
  if (Test-Path -LiteralPath $sampleDataPath) {
    $sampleFile = Get-Item -LiteralPath $sampleDataPath
    if ($sampleFile.Length -gt 0) {
      $sqlFiles += $sampleDataPath
    }
  }
}

foreach ($file in $sqlFiles) {
  if (-not (Test-Path -LiteralPath $file)) {
    throw "Required SQL file not found: $file"
  }
}

$separator = [Environment]::NewLine + [Environment]::NewLine
$sqlSections = foreach ($file in $sqlFiles) {
  Get-Content -LiteralPath $file -Raw
}
$combinedSql = $sqlSections -join $separator

if ($ResetDatabase) {
  $combinedSql = "DROP DATABASE IF EXISTS lawfirm;$separator$combinedSql"
}

$arguments = @(
  "--host=$ServerHost",
  "--port=$Port",
  "--user=$User",
  "--default-character-set=utf8mb4"
)

$env:MYSQL_PWD = $Password

try {
  $mysqlOutput = $combinedSql | & $mysqlExe @arguments 2>&1
  $exitCode = $LASTEXITCODE
}
finally {
  Remove-Item Env:MYSQL_PWD -ErrorAction SilentlyContinue
}

if ($exitCode -ne 0) {
  $outputText = ($mysqlOutput | Out-String).Trim()
  if ($outputText -match "already exists") {
    throw "The lawfirm database schema already exists. Run the script with -ResetDatabase if you want to recreate it from scratch."
  }

  if ($outputText) {
    throw "Database initialization failed: $outputText"
  }

  throw "Database initialization failed with exit code $exitCode."
}

if ($IncludeSampleData) {
  Initialize-SampleUploads -RepositoryRoot $repoRoot
}

Write-Host "Database initialization completed successfully."
Write-Host "Run backend/sql/tabular_reports.sql manually in mysql when you want the joined tabular demo output."
