import io
import mimetypes
import re
import zipfile
from pathlib import Path
from uuid import uuid4
from xml.sax.saxutils import escape

from fastapi import HTTPException, UploadFile
from fastapi.responses import FileResponse, Response
from pymysql import MySQLError

from ..db import execute, fetch_all, fetch_one

REPO_ROOT = Path(__file__).resolve().parents[3]
UPLOAD_DIR = REPO_ROOT / "uploads"
UPLOAD_DIR.mkdir(exist_ok=True)

PLACEHOLDER_MARKER = "Sample upload placeholder generated by backend/sql/init_db.ps1"


def _visible_file_name(file_name: str | None, file_path: str | None = None):
    raw_name = file_name or (file_path.split("/")[-1] if file_path else None) or "document.txt"
    return re.sub(r"^[a-f0-9]{32}_", "", raw_name, flags=re.IGNORECASE)


def _guess_media_type(file_name: str):
    media_type, _ = mimetypes.guess_type(file_name)
    return media_type or "application/octet-stream"


def _is_legacy_placeholder(path: Path):
    if not path.exists() or not path.is_file():
        return False

    try:
        head = path.read_bytes()[:512]
    except OSError:
        return False

    return PLACEHOLDER_MARKER.encode("utf-8") in head


def _document_placeholder_lines(document: dict, file_name: str):
    case_label = document.get("case_code") or f"Matter #{document.get('case_id') or document.get('document_id')}"
    case_title = document.get("case_title") or "Untitled matter"
    return [
        "Sample seeded document placeholder",
        f"Matter: {case_label}",
        f"Title: {case_title}",
        f"File: {file_name}",
        "Generated by the backend download fallback.",
        "Replace this seeded placeholder with a real file when needed.",
    ]


def _xlsx_column_name(index: int):
    name = ""
    current = index
    while current > 0:
        current, remainder = divmod(current - 1, 26)
        name = chr(65 + remainder) + name
    return name


def _build_xlsx_placeholder(document: dict, file_name: str):
    rows = [
        ("Section", "Value"),
        ("Matter", document.get("case_code") or f"Matter #{document.get('case_id') or document.get('document_id')}"),
        ("Title", document.get("case_title") or "Untitled matter"),
        ("Stored file", file_name),
        ("Source", "Backend generated seeded placeholder"),
        ("Action", "Replace with a real spreadsheet if needed"),
    ]

    sheet_rows = []
    for row_index, row in enumerate(rows, start=1):
        cells = []
        for column_index, value in enumerate(row, start=1):
            cell_ref = f"{_xlsx_column_name(column_index)}{row_index}"
            cells.append(
                f'<c r="{cell_ref}" t="inlineStr"><is><t xml:space="preserve">{escape(str(value))}</t></is></c>'
            )
        sheet_rows.append(f'<row r="{row_index}">{"".join(cells)}</row>')

    sheet_xml = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">'
        "<sheetData>"
        f'{"".join(sheet_rows)}'
        "</sheetData>"
        "</worksheet>"
    )

    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr(
            "[Content_Types].xml",
            """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>
  <Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>
  <Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>
</Types>""",
        )
        archive.writestr(
            "_rels/.rels",
            """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>
</Relationships>""",
        )
        archive.writestr(
            "xl/workbook.xml",
            """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <sheets>
    <sheet name="Placeholder" sheetId="1" r:id="rId1"/>
  </sheets>
</workbook>""",
        )
        archive.writestr(
            "xl/_rels/workbook.xml.rels",
            """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>
  <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>
</Relationships>""",
        )
        archive.writestr(
            "xl/styles.xml",
            """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <fonts count="1"><font><sz val="11"/><name val="Calibri"/></font></fonts>
  <fills count="1"><fill><patternFill patternType="none"/></fill></fills>
  <borders count="1"><border/></borders>
  <cellStyleXfs count="1"><xf/></cellStyleXfs>
  <cellXfs count="1"><xf xfId="0"/></cellXfs>
  <cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles>
</styleSheet>""",
        )
        archive.writestr("xl/worksheets/sheet1.xml", sheet_xml)

    return buffer.getvalue()


def _build_docx_placeholder(document: dict, file_name: str):
    paragraphs = "".join(
        f"<w:p><w:r><w:t>{escape(line)}</w:t></w:r></w:p>"
        for line in _document_placeholder_lines(document, file_name)
    )
    document_xml = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<w:document xmlns:wpc="http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas" '
        'xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" '
        'xmlns:o="urn:schemas-microsoft-com:office:office" '
        'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" '
        'xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" '
        'xmlns:v="urn:schemas-microsoft-com:vml" '
        'xmlns:wp14="http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing" '
        'xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" '
        'xmlns:w10="urn:schemas-microsoft-com:office:word" '
        'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
        'xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml" '
        'xmlns:w15="http://schemas.microsoft.com/office/word/2012/wordml" '
        'xmlns:wpg="http://schemas.microsoft.com/office/word/2010/wordprocessingGroup" '
        'xmlns:wpi="http://schemas.microsoft.com/office/word/2010/wordprocessingInk" '
        'xmlns:wne="http://schemas.microsoft.com/office/word/2006/wordml" '
        'xmlns:wps="http://schemas.microsoft.com/office/word/2010/wordprocessingShape" '
        'mc:Ignorable="w14 w15 wp14">'
        f"<w:body>{paragraphs}<w:sectPr><w:pgSz w:w=\"12240\" w:h=\"15840\"/><w:pgMar w:top=\"1440\" w:right=\"1440\" w:bottom=\"1440\" w:left=\"1440\"/></w:sectPr></w:body>"
        "</w:document>"
    )

    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr(
            "[Content_Types].xml",
            """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
</Types>""",
        )
        archive.writestr(
            "_rels/.rels",
            """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>""",
        )
        archive.writestr("word/document.xml", document_xml)

    return buffer.getvalue()


def _escape_pdf_text(value: str):
    return value.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


def _build_pdf_placeholder(document: dict, file_name: str):
    lines = _document_placeholder_lines(document, file_name)
    text_body = ["BT", "/F1 12 Tf", "14 TL", "72 760 Td"]
    for index, line in enumerate(lines):
        prefix = "" if index == 0 else "T* "
        text_body.append(f"{prefix}({_escape_pdf_text(line)}) Tj")
    text_body.append("ET")
    stream_content = "\n".join(text_body).encode("utf-8")

    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
        f"<< /Length {len(stream_content)} >>\nstream\n".encode("utf-8") + stream_content + b"\nendstream",
    ]

    chunks = [b"%PDF-1.4\n"]
    offsets: list[int] = []
    current_length = len(chunks[0])

    for index, obj in enumerate(objects, start=1):
        offsets.append(current_length)
        entry = f"{index} 0 obj\n".encode("utf-8") + obj + b"\nendobj\n"
        chunks.append(entry)
        current_length += len(entry)

    xref_offset = current_length
    xref_lines = [b"xref\n", f"0 {len(objects) + 1}\n".encode("utf-8"), b"0000000000 65535 f \n"]
    xref_lines.extend(f"{offset:010d} 00000 n \n".encode("utf-8") for offset in offsets)
    trailer = (
        b"trailer\n"
        + f"<< /Size {len(objects) + 1} /Root 1 0 R >>\n".encode("utf-8")
        + b"startxref\n"
        + f"{xref_offset}\n".encode("utf-8")
        + b"%%EOF"
    )

    return b"".join(chunks + xref_lines + [trailer])


def _build_text_placeholder(document: dict, file_name: str):
    return ("\n".join(_document_placeholder_lines(document, file_name)) + "\n").encode("utf-8")


def get_document_record(document_id: int):
    document = fetch_one(
        """
        SELECT
          document_id,
          case_id,
          confidentiality_level,
          file_path,
          file_url,
          file_name,
          created_at,
          case_code,
          case_title,
          uploaded_by_name
        FROM vw_document_register
        WHERE document_id = %s
        """,
        (document_id,),
    )
    if not document:
        raise HTTPException(status_code=404, detail="Document not found.")
    return document


def ensure_document_access(employee_id: int, document_id: int):
    result = fetch_one(
        "SELECT fn_can_view_document(%s, %s) AS allowed",
        (employee_id, document_id),
    )
    if not result or not result["allowed"]:
        execute(
            """
            CALL sp_log_access_violation(
              %s, 'Document', %s, 'VIEW_DOCUMENT',
              'Document denied by case access or clearance policy.', 'HIGH', NULL
            )
            """,
            (employee_id, document_id),
        )
        raise HTTPException(status_code=403, detail="You do not have clearance for this document.")


def list_documents(employee_id: int | None = None):
    if employee_id is None:
        return fetch_all(
            """
            SELECT
              document_id,
              case_id,
              uploaded_by,
              confidentiality_level,
              file_path,
              file_url,
              file_name,
              created_at,
              case_code,
              case_title,
              uploaded_by_name,
              latest_version,
              version_count,
              last_modified_at
            FROM vw_document_register
            ORDER BY created_at DESC, document_id DESC
            """
        )

    return fetch_all(
        """
        SELECT
          document_id,
          case_id,
          uploaded_by,
          confidentiality_level,
          file_path,
          file_url,
          file_name,
          created_at,
          case_code,
          case_title,
          uploaded_by_name,
          latest_version,
          version_count,
          last_modified_at
        FROM vw_document_register
        WHERE fn_can_view_document(%s, document_id)
        ORDER BY created_at DESC, document_id DESC
        """,
        (employee_id,),
    )


def list_case_documents(case_id: int):
    return {
        "case_id": case_id,
        "documents": fetch_all(
            """
            SELECT
              document_id,
              case_id,
              uploaded_by,
              uploaded_by_name,
              confidentiality_level,
              file_path,
              file_url,
              file_name,
              created_at,
              latest_version,
              version_count,
              last_modified_at
            FROM vw_document_register
            WHERE case_id = %s
            ORDER BY created_at DESC, document_id DESC
            """,
            (case_id,),
        ),
    }


def build_document_download_response(document: dict):
    visible_name = _visible_file_name(document.get("file_name"), document.get("file_path"))
    file_path_value = document.get("file_path")
    stored_path = REPO_ROOT / file_path_value if file_path_value else None

    if stored_path and stored_path.exists() and not _is_legacy_placeholder(stored_path):
        return FileResponse(
            stored_path,
            media_type=_guess_media_type(visible_name),
            filename=visible_name,
        )

    extension = Path(visible_name).suffix.lower()
    if extension == ".xlsx":
        payload = _build_xlsx_placeholder(document, visible_name)
        media_type = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    elif extension == ".docx":
        payload = _build_docx_placeholder(document, visible_name)
        media_type = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    elif extension == ".pdf":
        payload = _build_pdf_placeholder(document, visible_name)
        media_type = "application/pdf"
    else:
        payload = _build_text_placeholder(document, visible_name)
        media_type = "text/plain; charset=utf-8"

    headers = {"Content-Disposition": f'attachment; filename="{visible_name}"'}
    return Response(content=payload, media_type=media_type, headers=headers)


async def save_document_upload(
    *,
    case_id: int,
    file: UploadFile,
    uploaded_by: int | None,
    confidentiality_level: str,
):
    if not file.filename:
        raise HTTPException(status_code=400, detail="Please choose a file to upload.")

    safe_name = Path(file.filename).name
    stored_name = f"{uuid4().hex}_{safe_name}"
    stored_path = UPLOAD_DIR / stored_name

    with stored_path.open("wb") as buffer:
        while chunk := await file.read(1024 * 1024):
            buffer.write(chunk)

    try:
        document_id = execute(
            """
            INSERT INTO Document(case_id, uploaded_by, confidentiality_level, file_path)
            VALUES (%s, %s, %s, %s)
            """,
            (case_id, uploaded_by, confidentiality_level, f"uploads/{stored_name}"),
        )
    except MySQLError as exc:
        stored_path.unlink(missing_ok=True)
        raise HTTPException(status_code=400, detail=str(exc)) from exc

    return {
        "message": "Uploaded",
        "document_id": document_id,
        "file_name": safe_name,
        "file_path": f"uploads/{stored_name}",
        "file_url": f"/uploads/{stored_name}",
    }
